### PR TITLE
renaming and restructuring

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
Note I have made a simplification which eliminates the need of a default ServletContextHelper by using the default one which is always available to the Http Whiteboard.

this ensures re-rooting is supported without any implementation on the JAX-RS side.

**Comment by rotty3000** [comment]
we should probably disable the listing view of the JAX-RS endpoints as discussed.

**Comment by rotty3000** [comment]
i.e. the path to the endpoints is now `http://localhost:8080/examples/example-addon` and `http://localhost:8080/example-application`

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request merged**
